[package]
name = "zfp-sys"
version = "0.1.4"
authors = ["jvo203 <chris.zapart@nao.ac.jp>"]
edition = "2018"
description = "Raw Rust bindings to ZFP (https://github.com/LLNL/zfp)."
repository = "https://github.com/jvo203/zfp-sys"
license = "MIT"
categories = ["compression", "external-ffi-bindings", "science"]

[build-dependencies]
bindgen = "0.47.1"
cmake = "0.1.35"

[features]
default = []
cuda = []